engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 45
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
